version: '3.1'

services:
   db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: admin
         MYSQL_USER: admin
         MYSQL_PASSWORD: admin
         MYSQL_DATABASE: api_mysql
      ports:
         - 3308:3306

   db_test:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: admin
         MYSQL_USER: admin
         MYSQL_PASSWORD: admin
         MYSQL_DATABASE: api_mysql_test
      ports:
         - 3307:3306
